FROM php:8.4-apache

# Install system dependencies
RUN apt-get update && \
    apt-get install -y libzip-dev && \
    docker-php-ext-install zip && \
    apt-get install -y certbot python3-certbot-apache && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN a2enmod rewrite && \
    a2enmod ssl

WORKDIR /var/www/html

RUN cp /usr/local/etc/php/php.ini-development /usr/local/etc/php/php.ini && \
    sed -i 's/upload_max_filesize.*/upload_max_filesize = 32M/' /usr/local/etc/php/php.ini && \
    sed -i 's/post_max_size.*/post_max_size = 32M/' /usr/local/etc/php/php.ini && \
    sed -i 's/memory_limit.*/memory_limit = 256M/' /usr/local/etc/php/php.ini && \
    sed -i 's/max_execution_time.*/max_execution_time = 60/' /usr/local/etc/php/php.ini

