FROM php:8.4-apache

# Install system dependencies
RUN apt-get update && \
    apt-get install -y libzip-dev && \
    docker-php-ext-install zip && \
    apt-get install -y certbot python3-certbot-apache && \
    # Cleanup
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN a2enmod rewrite && \
    a2enmod ssl

WORKDIR /var/www/html

RUN cp /usr/local/etc/php/php.ini-development /usr/local/etc/php/php.ini
